seeds = [0, 1, 212312388123, 123]

[[scenario]]
sim = "GossipSingle"
nodes = 20
config.membership = { active_view_capacity = 10 }

[[scenario]]
sim = "GossipSingle"
nodes = 100

[[scenario]]
sim = "GossipSingle"
nodes = 1000

[[scenario]]
sim = "GossipMulti"
nodes = 20

[[scenario]]
sim = "GossipMulti"
nodes = 100

[[scenario]]
sim = "GossipMulti"
nodes = 1000
config.membership.active_view_size = 10

[[scenario]]
sim = "GossipAll"
nodes = 20

[[scenario]]
sim = "GossipAll"
nodes = 100
rounds = 5

# [[scenario]]
# sim = "GossipAll"
# nodes = 500
# rounds = 5
