name: run simulations
on:
  pull_request:

jobs:
  run_sim:
    runs-on: ubuntu-latest
    env:
      RUSTC_WRAPPER: "sccache"
      SCCACHE_GHA_ENABLED: "on"
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Install rust stable
        uses: dtolnay/rust-toolchain@6c977a6ca4077a0ceb28ffbe03f59d46e9ac8772 # v1
        with:
          toolchain: stable

      - name: Install sccache
        uses: mozilla-actions/sccache-action@7d986dd989559c6ecdb630a3fd2557667be217ad # v0.0.9

      - name: Run simulations
        run: |
          git checkout ${{ github.event.pull_request.base.ref }}
          cargo run -q --locked --bin sim --features simulator --release -- run -c simulations/all.toml -o /tmp/sim-main
          git checkout ${{ github.event.pull_request.head.sha }}
          cargo run -q --locked --bin sim --features simulator --release -- run -c simulations/all.toml -o /tmp/sim-pr --baseline /tmp/sim-main |& tee REPORT
          echo "<details><summary>Simulation report</summary>" >> COMMENT
          echo "" >> COMMENT
          echo '```' >> COMMENT
          cat REPORT >> COMMENT
          echo "" >> COMMENT
          echo '```' >> COMMENT
          echo "</details>" >> COMMENT
          echo "" >> COMMENT
          echo "*Last updated: $(date -u +'%Y-%m-%dT%H:%M:%SZ')*" >> COMMENT

      - name: Find Docs Comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number || inputs.pr_number }}
          comment-author: "github-actions[bot]"
          body-includes: Simulation report

      - name: Create or Update Docs Comment
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.pull_request.number || inputs.pr_number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          body-path: COMMENT
          edit-mode: replace
